version: '3.8'

services:
  kyros-assistant:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_KEY=${API_KEY}
    image: kyros-data-assistant:latest
    container_name: kyros_app
    ports:
      - "8080:80"
    environment:
      - API_KEY=${API_KEY}
    restart: always
